name          'example42-stdmod'
version '0.0.3'
author        'STDMOD contributors'
project_page  'https://github.com/stdmod'
source        'https://github.com/stdmod/stdmod'
license       'Apache License, Version 2.0'
summary       'This is the common module for stdmod compliant modules'
description   'This module provides functions and resources used by stdmod modules based on the https://github.com/stdmod/puppet-skeletons. It is published on the Forge under the example42 account because it was not possible to create a stdmod user.'
dependency    'puppetlabs/stdlib'
